### ISSUE TITLE
Extra spacing above top heading in a callout

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/ui-core#1]
From this doc

```
    {{
    docCallout (Some {{ 🤔 }}) 
      {{ 
      ## What about LLVM?
    
      Blah blah blah  
      }}
    }}
```

We get

<img width="666" alt="image" src="https://user-images.githubusercontent.com/11074/160486807-6a39bc09-3df3-46db-8c44-7ccc8ad445ce.png">

**Comment by hojberg** [comment]
This has been fixed it appears.
