### ISSUE TITLE
Clickable links for namespace segments

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/ui-core#28]
For example if I am currently viewing the `public.base.latest.Either` namespace, it feels like I should be able to click on the `base` segment of the path to change my perspective to `unison.base`.

If this were to be added, it may be reasonable to remove the arrow that goes up one level, because it would be just as easy to click on the parent segment.

<img width="252" alt="Screen Shot 2022-08-20 at 9 12 31 AM" src="https://user-images.githubusercontent.com/977929/185747753-7dc1e505-e58c-46a3-bd61-f710da84709e.png">

**Comment by hojberg** [comment]
I think this is a natural and probably expected interaction to add.
The challenge is with the cropped part, but maybe its fine to say you can only click up and to `base` in the above example and if you want further up you can click on the following screen.

We might also add a "jump to" interaction 🤔

**Comment by ceedubs** [comment]
@hojberg I think that would be fine for now and still an improvement.

**Comment by hojberg** [comment]
Done :)
