### ISSUE TITLE
Render mermaid diagrams

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/ui-core#29]
I don't really have a current use-case for this, but I think that it would be cool if doc rendering could use [mermaid.js](https://mermaid-js.github.io/mermaid/#/) to render mermaid diagrams. This is something [supported by GitHub](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/).

The most obvious way to do it would be to render code blocks with the `mermaid` language label, like:

````
```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```
````

This would render as:

```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```

But since `Doc` is a regular Unison data type, the UI could potentially support some more programmatic way of creating diagrams. Even then I think that it would be nice to support the simple markdown format.

**Comment by hojberg** [comment]
This would be really cool!

**Comment by dolio** [comment]
This is actually complete.
