### ISSUE TITLE
Rendering issues with nested lists on Firefox

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/ui-core#30]
https://share.unison-lang.org/@unison/code/latest/namespaces/public/distributed/main/;/types/@mhi2komccqobf4i8240ldrfck4sprclnkiac52nv1connp36laofhern1q83dpco84bme03jfts50n0t84b7djl20mnup9tbujratdg.1

<img width="796" alt="image" src="https://user-images.githubusercontent.com/11074/186504086-199c52e4-0be0-45df-ab64-6b1c9d019dd4.png">

**Comment by hojberg** [comment]
Fixed by https://github.com/unisonweb/ui-core/commit/51bcc897e0829ffe264979f93383e2d35daf1ea4
