### ISSUE TITLE
Set up Storybook for UI components

### ISSUE THREAD

**Issue by hojberg** [unisonweb/ui-core#31]
Check out https://github.com/ryannhg/elm-storybook-example as inspiration for setup.

**Comment by yoching** [comment]
I've added some UI elements. 

<img width="822" alt="Screenshot 2022-12-21 at 18 51 51" src="https://user-images.githubusercontent.com/3376690/208971896-bb86763e-d3ea-495f-98b8-fbd4f81b9d0c.png">

Any feedback is appreciated.

This is the repository.
https://github.com/yoching/unison-ui-core-storybook

**Comment by hojberg** [comment]
Nice, this is awesome! Would love to figure out how get this running inside of the ui-core repository

**Comment by yoching** [comment]
Progress:
Showing source from manually constructed source model.

<img width="862" alt="Screenshot 2023-01-06 at 16 26 46" src="https://user-images.githubusercontent.com/3376690/211043344-14cf9f68-221c-4afa-bd8c-65c97d477503.png">

**Comment by hojberg** [comment]
Yay we can close this one now! Thanks again @yoching
