### ISSUE TITLE
Doc wrapping on mobile

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/ui-core#53]
![Screenshot_20221119-004120_Brave](https://user-images.githubusercontent.com/11074/202826039-ff82875f-ba86-4610-b244-a2984e4b4932.png)
![Screenshot_20221119-003908_Brave](https://user-images.githubusercontent.com/11074/202826042-dc482ce2-3116-4dbc-8f9c-729b50db2f72.png)

**Comment by hojberg** [comment]
This has been fixed today.
