### ISSUE TITLE
When `getDefinition` returns more than 1 result, only the first is displayed

### ISSUE THREAD

**Issue by hojberg** [unisonweb/ui-core#68]
When `getDefinition` returns more than 1 result, we cut a corner and just render the first one in the list. Its rare that you have 2 things named the same, but can occur with smart constructors like in this example from community member Kristian Notari (who reported this issue):

![image](https://github.com/unisonweb/ui-core/assets/2371/91b826f7-4f27-4592-9a89-3ec4956d8f08)

We should just render all definitions that were returned, and focus the first one.

**Comment by yoching** [comment]
I've been working on this issue.
Please see this branch if you're interested!

https://github.com/yoching/ui-core/tree/fix-multiple-definition
