### ISSUE TITLE
Add a “jump-to” modal for quick navigation with many opened definitions

### ISSUE THREAD

**Issue by hojberg** [unisonweb/ui-core#7]
If the user has a many open definitions we can remidy that by allowing a modal that appears on a specific keyboard shortcut that shows all the open definitions in a compact form allowing for quicker scroll and overview of them as well as selecting one directly from the modal to update the main content area.

An alternative to this could be a “mini-map” like feature that would show on the right hand side.

**Comment by hojberg** [comment]
The mini-map approach has been explored in the design space and seems quite promising and very easy to implement:

<img width="260" alt="Map" src="https://user-images.githubusercontent.com/2371/197569004-a271042c-f230-403a-b8ba-de1d67a55765.png">

**Comment by yoching** [comment]
@hojberg 
I'm thinking about working on this issue. Does this Minimap view component already exist in the codebase?

**Comment by hojberg** [comment]
Nice. No, this would be a new module (or perhaps be collocated within another) in the Code section I think. It can use the WorkspaceItems type to get the current open items.
