### ISSUE TITLE
Fit documentation into available width on the screen (desktops)

### ISSUE THREAD

**Issue by andreystepanov** [unisonweb/ui-core#80]
This documentation must be able to fit the screen, without adding vertical scroll.

https://share.unison-lang.org/@unison/base/code/releases/2.12.0/latest/types/reflection/Rewrites

![shot-2024-01-25-at-23-40-42--area](https://github.com/unisonweb/ui-core/assets/472885/442ad3a4-898a-492d-93cc-c99c4bb1ae70)

![shot-2024-01-25-at-23-41-01--area](https://github.com/unisonweb/ui-core/assets/472885/28c7495f-974c-48d5-b1d0-fb44ed3d2808)

**Comment by hojberg** [comment]
Fixed by #86
