### ISSUE TITLE
Minimap breaks layout when it gets too long

### ISSUE THREAD

**Issue by andreystepanov** [unisonweb/ui-core#81]
When minimap gets too long (while exploring big libraries like `base`) it creates some weird empty spots in UI.

To fix this, we might limit `workspace-minimap` height to available viewport height (`max-height: 80vh` looks ok, see screenshot).

### Current
![shot-2024-01-28-at-14-03-06--area](https://github.com/unisonweb/ui-core/assets/472885/c2bd59dc-8282-4246-bcde-1432b83f53bc)

### With `max-height: 80vh; overflow: auto;` fix
![shot-2024-01-28-at-14-11-16--area](https://github.com/unisonweb/ui-core/assets/472885/18d606ef-95ca-4398-ac83-05eb98cd5459)

**Comment by hojberg** [comment]
Hmmmm this might be ok for now, but the magic of `80vh` might bite us in the foot later. Seems like something we'd forget to adjust if the header ever changes height. 🤔

**Comment by jcwilk** [comment]
+1, I'm constantly battling the empty space on the bottom of the screen from this :sweat_smile: maybe I'll add a css adjustment extension to hold me over with andrey's suggestion

**Comment by jcwilk** [comment]
FWIW I had better luck limiting the height of `workspace-minimap_entries` so the "close all" headers etc don't get scrolled, eye of the beholder maybe

![Screenshot_2024-02-06_14-27-58](https://github.com/unisonweb/ui-core/assets/39782/eb71441a-d488-497c-b62c-8b7a3c424680)

**Comment by hojberg** [comment]
This was fixed by #84
