### ISSUE TITLE
`clone` command in `Use Project` modal should include currently selected branch

### ISSUE THREAD

**Issue by andreystepanov** [unisonweb/ui-core#82]
`clone` command in `Use Project` modal window should include currently selected branch.

![shot-2024-02-08-at-13-01-28--area](https://github.com/unisonweb/ui-core/assets/472885/aee1e82a-65a2-4aa6-9280-306a87c0ddbe)

The correct `clone` command in the screenshot above should be (hence the hint):

`.> clone clone @unison/base/@andreystepanov/fix-stm-code-example`

Live link:

https://share.unison-lang.org/@unison/base/code/@andreystepanov/fix-stm-code-example/latest

**Comment by hojberg** [comment]
@andreystepanov good catch. We now show the branch; makes it simpler.
