### ISSUE TITLE
Consider adding `close` action for each minimap item

### ISSUE THREAD

**Issue by andreystepanov** [unisonweb/ui-core#85]
While exploring codebase, i can't close top-most opened definition, because controls are hidden behind minimap menu. 

_Granted, it happens only if some other definition requires more space, which makes all opened definitions the same width._

### Example with opened minimap

![shot-2024-03-28-at-13-05-53--area](https://github.com/unisonweb/ui-core/assets/472885/6d9d400b-3eb7-4d0c-bbe7-0a3fad4a11cc)

### Example with collapsed minimap

Logical next step is to collapse minimap, but it doesn't help. You still need to "hunt" for that close button (only small part of it is visible).

![shot-2024-03-28-at-13-06-28--area](https://github.com/unisonweb/ui-core/assets/472885/0bd3ce8a-de55-4264-acde-1512c7c5ab31)

### Possible solution

The solution to all of these edge-cases might be as simple as adding `close` action to each item in minimap, in addition to `close` buttons inside definition blocks itself.

_For inactive items (not currently selected definition) `close` action might be visible only on `hover`, if needed (to keep it clean)._

![shot-2024-03-28-at-13-25-28--area](https://github.com/unisonweb/ui-core/assets/472885/87bf2e9f-f969-44c3-a16e-26757daf45eb)

**Comment by hojberg** [comment]
Having an x on the minimap items sounds great, but we need to fix the bigger issues of weirdly wide open definitions

**Comment by hojberg** [comment]
Just added this 🎉

**Comment by andreystepanov** [comment]
Looking gooood :)

Thanks, Simon!
